---
- hosts: ajbell_test
  become: yes
  tasks:

  - name: Changing jhcadmin and root password
    user:
      name: "{{ item.name }}"
      password: "{{ item.password }}"
    with_items:
      - { name: jhcadmin, password: $6$s9EM8.06/zaFRZcb$haC2tEyOW3gFgIRkgckWUqSHNaPE2MvNYmf1hdXKtLU6uycU78DVK0lSTx26idNtoHZnW1gmt/Ez13PzclHmv/ }
      - { name: root, password: $6$vE5uGtvm3AK10Cgh$PFqC14BMvHIH5P7I/7b5g8haBcZkODC0LkMZwsFqF9cuOk9CEi3tG7SXHKQFhDjI7ZkC7bkNnq1SJXX/h2q721 }
